version: '3'
services:
  node-environment:
    image: node:${NODE_VERSION}-alpine
    volumes:
      - ./:/var/www/html
    ports: 
      - ${SERVER_PORT}:80
    working_dir: /var/www/html
    command: npm run start:${NODE_ENVIRONMENT}